### ISSUE TITLE
Link do działającej wersji online do opisu, proszę!

### ISSUE THREAD

**Issue by yyx990805** [nathell/wybory2023#1]
Uprzejmie proszę o dodanie linku do strony do opisu repozytorium (jest takie pole w ikonce trybiku)
(w ten sposó” ma to taką zaletę, że adres strony nie wędruje do historii commitów w repo w przeciwieństwie do umieszczenia go w README repo)

(bo backlink ze strony do repo już jest :) )

**Comment by nathell** [comment]
Bardzo proszę, już jest. :)
